M48
; DRILL file {KiCad 7.0.9-7.0.9~ubuntu20.04.1} date Thu 28 Dec 2023 04:07:46 GMT
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-12-28T04:07:46+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9-7.0.9~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,8,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.991
%
G90
G05
T1
X108.99Y-69.82
X119.405Y-77.975
T2
X100.724Y-72.58
X101.74Y-67.5
X102.756Y-72.58
T0
M30
