[target.'cfg(all(target_arch = "arm", target_os = "none"))']

# nRF5340 audio dk
runner = "probe-rs run --chip nRF5340_xxAA --allow-erase-all --probe 1366:1051"

# yote
#runner = "probe-rs run --chip nRF5340_xxAA --allow-erase-all --probe 1366:0101"

rustflags = ["-C", "link-arg=-Tlink.x", "-C", "link-arg=-Tdefmt.x"]

[build]
target = "thumbv8m.main-none-eabihf" # = ARM Cortex-M33

[env]
# run this for normal operation
DEFMT_LOG = "info"

# run this for reduced logging
#DEFMT_LOG = "warn"
